# Generated by Django 4.2.1 on 2023-06-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='pronouns',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
